vars:
  version: 3.0.0
  tcl-source-location: http://archive.ubuntu.com/ubuntu/pool/universe/t/tcl8.4/tcl8.4_8.4.20.orig.tar.gz
  tcl-expected-sha256: fcb317b65c69f1d6962057c5622a80980bc22ffadf25c1cc50b6d02ff6c2cf40
  package: libtcl-irulescan
package:
  name: ${{vars.package}}
  version: ${{vars.version}}
  epoch: 0
  description: "..."
  copyright:
    - license: MIT
  target-architecture:
    #- x86_64
    - aarch64

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
      - ./melange.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - ca-certificates-bundle
      - glibc
#  contents:
#    keyring:
#      #- https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
#      - ./signkeys/alpine-devel@lists.alpinelinux.org-4a6a0840.rsa.pub
#      - ./signkeys/alpine-devel@lists.alpinelinux.org-6165ee59.rsa.pub
#      - ./signkeys/alpine-devel@lists.alpinelinux.org-5261cecb.rsa.pub
#      - ./signkeys/alpine-devel@lists.alpinelinux.org-61666e3f.rsa.pub
#      - ./signkeys/alpine-devel@lists.alpinelinux.org-5243ef4b.rsa.pub
#    repositories:
#      - https://dl-cdn.alpinelinux.org/alpine/v3.21/main
#    packages:
#      - alpine-base
#      - build-base
#      - boost-dev
#      - libsodium-dev
#      - sqlite-dev
#      - lua5.4-dev
#      - openssl-dev

pipeline:
  - uses: fetch
    with:
      uri: ${{vars.tcl-source-location}}
      expected-sha256: ${{vars.tcl-expected-sha256}}

  - uses: autoconf/configure
    with:
      opts: |
        --enable-64bit \
        --prefix=/usr

  - uses: autoconf/make

  - uses: strip

  - runs: |
      PACKAGE_DIR="${{targets.destdir}}"
      if [ -n "${{vars.package}}" ]; then
        PACKAGE_DIR="${{targets.outdir}}/${{vars.package}}"
      fi

      if [ "$PACKAGE_DIR" == "${{targets.contextdir}}" ]; then
        echo "ERROR: Package can not split files from itself!" && exit 1
      fi

      mv "$PACKAGE_DIR"/usr/lib/libtcl8.4.so "${{targets.contextdir}}"/usr/lib/libtcl-irulescan.so
      mkdir -p "${{targets.contextdir}}"/usr/share/licenses/tcl8.4

      cp -a license.terms "${{targets.contextdir}}"/usr/share/licenses/tcl8.4/license.terms


subpackages:
  - name: "libtcl-irulescan-dev"
    description: "Clienttools for pdns"
    pipeline:
      - runs: |
          PACKAGE_DIR="${{targets.destdir}}"
          if [ -n "${{vars.package}}" ]; then
            PACKAGE_DIR="${{targets.outdir}}/${{vars.package}}"
          fi

          if [ "$PACKAGE_DIR" == "${{targets.contextdir}}" ]; then
            echo "ERROR: Package can not split files from itself!" && exit 1
          fi

          mv "$PACKAGE_DIR"/usr/include/tcl.h "${{targets.contextdir}}"/usr/include/tcl.h
          mv "$PACKAGE_DIR"/usr/include/tclDecls.h "${{targets.contextdir}}"/usr/include/tclDecls.h
          mv "$PACKAGE_DIR"/usr/include/tclPlatDecls.h "${{targets.contextdir}}"/usr/include/tclPlatDecls.h

          mkdir -p "${{targets.contextdir}}"/usr/share/licenses/tcl8.4
          cp -a license.terms "${{targets.contextdir}}"/usr/share/licenses/tcl8.4/license.terms

