name: Release

on:
  workflow_dispatch:
  release:
    types: [released]

jobs:
  release:
    strategy:
      matrix:
        containers:
          - file: files/Dockerfile
            tags: |
              simonkowallik/irulescan:latest
              ghcr.io/simonkowallik/irulescan:latest
          - file: files/Dockerfile.apiserver
            tags: |
              simonkowallik/irulescan:apiserver
              ghcr.io/simonkowallik/irulescan:apiserver
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          file: ${{ matrix.containers.file }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ matrix.containers.tags }}

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          # docker... https://github.com/peter-evans/dockerhub-description/issues/10
          password: ${{ secrets.DOCKERHUB_PASSWORD }}